<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaItem extends BaseCategoriaItem
{
  public function __toString(){
    return $this->nombre ? $this->nombre : ''; //se cumple la pregunta? si : no 
  }
}
