<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaCampaign extends BaseCategoriaCampaign
{
  public function __toString(){
    return $this->nombre;
  }
}

