<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Impresor extends BaseImpresor
{
  public function __toString(){
    return $this->nombre ? $this->nombre : '';
  }

}
