<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Item extends BaseItem
{
  public function preInsert($event)
  {
    $this->position = $this->getTable()->getNextPosition($this->campaign_id, $this->plaza_id);
  }
}
