<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mensajeria extends BaseMensajeria
{
  public function __toString(){
    return $this->nombre ? $this->nombre: '';
  }

}
