categoria_campaign:
  class: sfDoctrineRouteCollection
  options:
    model:               CategoriaCampaign
    module:              categoria_campaign
    prefix_path:         categoria_campaign
    column:              id
    with_wildcard_routes: true

campaign:
  class: sfDoctrineRouteCollection
  options:
    model:  Campaign

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
