mensajeria:
  class: sfDoctrineRouteCollection
  options:
    model:               Mensajeria
    module:              mensajeria
    prefix_path:         mensajeria
    column:              id
    with_wildcard_routes: true

impresor:
  class: sfDoctrineRouteCollection
  options:
    model:               Impresor
    module:              impresor
    prefix_path:         impresor
    column:              id
    with_wildcard_routes: true

tipo:
  class: sfDoctrineRouteCollection
  options:
    model:               Tipo
    module:              tipo
    prefix_path:         tipo
    column:              id
    with_wildcard_routes: true

plaza:
  class: sfDoctrineRouteCollection
  options:
    model:               Plaza
    module:              plaza
    prefix_path:         plaza
    column:              id
    with_wildcard_routes: true

categoria_item:
  class: sfDoctrineRouteCollection
  options:
    model:               CategoriaItem
    module:              categoria_item
    prefix_path:         categoria_item
    column:              id
    with_wildcard_routes: true

specialty:
  class: sfDoctrineRouteCollection
  options:
    model:               Specialty
    module:              specialty
    prefix_path:         specialty
    column:              id
    with_wildcard_routes: true

producto:
  class: sfDoctrineRouteCollection
  options:
    model:               Producto
    module:              producto
    prefix_path:         producto
    column:              id
    with_wildcard_routes: true

categoria_campaign:
  class: sfDoctrineRouteCollection
  options:
    model:               CategoriaCampaign
    module:              categoria_campaign
    prefix_path:         categoria_campaign
    column:              id
    with_wildcard_routes: true

campaign:
  class: sfDoctrineRouteCollection
  options:
    model:  Campaign
    object_actions: { addItems: get, createItems: post }


# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
