dev:
  doctrine:
    param:

test:
  doctrine:
    param:

all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=cerebro;host=localhost
      username:   cerebro_user
      password:   cerebro_pwd
      encoding:   utf8
      persistent: true
      pooling:    true
