generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Plaza
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          plaza
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Plazas
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
